language: node_js
node_js:
  - '10'
before_install: bash bin/ci-start-notify
script: yarn build
before_deploy:
  - yarn global add netlify-cli
  - yarn global add now
deploy:
  provider: script
  script: bash bin/ci-deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^staging|production$"
env:
  global:
    - secure: cEkQYol4gm69URXE0D4Y1x66/qINYZSPYCpsdSn738KY79gzjbvEH497hiBlikGDCGoF5fDpnb/29DxUuCjV1ySY+SWjSlV0WUPD3CEOV4fP08Ivx3BOSU8hks6UJfNQTS8rTKmY6lyoZD8GAzlIEgb14cwA9oOGNtG+3KqUtOqW/CQx/UGcSyMU4sCz4EHAwevM51lLzQ4T1k5qfloxNuGN62IiAsB/6nbWWLikdIa4vktPgbk1d5Q+HKLOtsJyGqTOoszt6xqF/cV3qdTrwDlMDJ53ylwbwpMIFkAzs9O8wNfPCF21j29Ku3671+9uE/2MmluC7dg7JRP+wp5GSH6HC0Ocr36kAQDgZjoy1MGzeN5JZZnOUeGXSDuIMW3JEwJT3e9Fk+7pmAY+tFw3PlOj2ualHk6k/vmrCYjMrWkbhvqSZrVRKVxYsKZ+K2GWnapm5akVzEJl6kh29Bh3k2drGsCSdW4AnSbIFK5gDAmDfOvtcTasa5YvHGSc+yHJuYVYA95eXhokh5YFhZyn31VcSgBksA7LVQWqRZWSOMSrBf9rG1qP8ElE8mdvM1Cn4brWgCXhzSMU53FWraclGuaRhqxywaA+PHO3nGNsGCXkucCZSqeYQVL/9aRVdxftU37qlozSp5y1+mxBViL/wMvbfdW4eqAGb1uCS+V1Y+Q=
    - secure: sXBf3Q5gkbpqZllxay2F0Xc5ifityMEfM6Qxm4+PYHTty8icNp0Y5odhFE2imOB8Or9XoeEJP1WUGdWFK+UVT6rr2/mvw3A9nJ/4sepr+KrQpI+y2lUYn2DTur11fIJG0tVXLWRn4V2ak1P5BJzwk6NdOfrOk7x/2opwLpzLXgiRqehqrkqSBsDaqatpxTCIKC4WRWxXYwehLJpZXUZsR1O89u89E3OsPjLeySGsuU8KUv57Pw7P42SEPbHg0z8LyxyDMAN871bLS4JbvMjs0TihJxncMY0htstTRVoHWt5fsB+WF9kRM+nL+P3lqTQ8xBKoXWT0ZEKB8W2W9pSgd1Llc7rkPBRckd/ym43VSUa8D5q2vmkFd+YyqKtQn80wz3yjq/AryDAWWa32b9FQmSSUUOuRXW1Q4453T/rc7QMyYxx+0U13pCtY+OMbfSiUXmanaEb2x6aRU0fAXq/7TfLRdNx6NlWGYb+IoRLWJ4qMt3yURMZ+UB2h4i2vxoDBrA0hQ1uA9FC4RudvEpYYf7i2Xtyta6sQlB66TvKBDkk5cyGQSG2ZfN2ZwSGH4uqw2Q7eyLpuKCK5m+2Y/J4zVBLlJzDdmD4wODQpqnfbXn+uPhVTR0AHAs9lwG/skGtSPmqtC9QLCc2W8lk4JKcP6mkAsSNlniAzjJ3c133vxNo=
    - secure: ZJRqcpkanFgWjyiWLThSEaWhg41JF69F8vDkhMDRS5VdmFmep8h6MFFuvpa18LQynxUN083QrS0WDDPjk3psxQPotTxeei/GXn1RruA8rKuOTZeQljH91Ne+cVwmWx8OjxutOBP0FnSzS7k0lUHUJUZbSsoZTtxgR0P/TyALHCZ5sofMvdQYaF/PhpCHZLLslbhkmKTyKDEHW7uW/DzIBao1bsmzutOJ+7w8ryPIdAlcy460JlfbPlDlL8vcqPKQsOKvSk39QnO/fPeM0egrmrwCRltWQ6HRrk0+O7+Qcx22gkKuOhkk8JsKFidw+7prveY3M+c8eb+hu3nuTbhs9Eq7pGl9dnbYv+cTdOREwfDKkDyqYIjfihaY0ILI+GLHSvmS8mH08DltBO9cxIHQCgpTe3MlbH+DxoVMlutweYoNzPts0FEcFElk3RdqGyEwqBl2mnm3MxX+cUp2LwRfcQyKqn3WV7Aiz7Kimn0i0ZWwkeWCu16DU3kAX1rqOJYSpLLCny7qd7aogAlBW6Y1T4Qm4uTmLrXMWQiaC2Z1JkOB3NnSB00reTZcgxTEWa0dfrKl9VS4iEaxI77B9NewUm4CiL6wNDFBu4KU5OuUTZ9TOLlySHJg2fS92kh4a9HxUNU4qWaBunzeu5OHhtIfr7Hwiayd6L8xX5unzTEolVs=
